### ISSUE TITLE
Being able to use markdown in docs (files, module docs, function/class docs)

### ISSUE THREAD

**Issue by thorwhalen** [i2mint/epythet#1]
- What possibilities does sphinx offer for markdown?
  - pros and cons (rst more functional, md easier to start with but what are we sacrificing?)?
  - Try out https://www.sphinx-doc.org/en/master/usage/markdown.html
  - integrate with CI (isee)

**Comment by sylvainbonnot** [comment]
Here are some thoughts on that:

- sphinx offers some support for markdown: https://myst-parser.readthedocs.io/en/latest/sphinx/intro.html, allowing to use .md files instead of .rst files to generate the docs. 
- even with myst-parser, sphinx cannot at the moment convert markdown written within the docstrings
- pros of md: easier syntax, more people can read and write it
- workaround to convert markdown written inside a docstring (I checked it worked with sphinx, did not check yet with epythet): 
  - pip install commonmark
  - inside the conf.py file of the sphinx doc, include this snippet: 
  ```
    import commonmark

    def docstring(app, what, name, obj, options, lines):
        md  = '\n'.join(lines)
        ast = commonmark.Parser().parse(md)
        rst = commonmark.ReStructuredTextRenderer().render(ast)
        lines.clear()
        lines += rst.splitlines()

    def setup(app):
        app.connect('autodoc-process-docstring', docstring)
    ```

**Comment by thorwhalen** [comment]
That could work. How/where do we integrate with `epythet`. See with @andeaseme .

**Comment by thorwhalen** [comment]
Can you include some reference about how there's no support for md-parsing module's and function's docstrings in sphinx? Seems like if they can do it with files, docstrings shouldn't be too far away.

**Comment by sylvainbonnot** [comment]
Done: the fact that sphinx, even with the myst-parser extension cannot do autodoc on functions docstrings without a hack is documented in that issue : [no md docstring](https://github.com/executablebooks/MyST-Parser/issues/228).

**Comment by sylvainbonnot** [comment]
This has been integrated in my fork of epythet: https://github.com/sylvainbonnot/epythet/blob/dev-sylvain/epythet/_static/docsrc/conf.py

In short: markdown within docstrings can be read by epythet. 

Here is an example with a code block within docstrings:
![Screen Shot 2021-09-22 at 10 41 15](https://user-images.githubusercontent.com/17656072/134355023-8721e291-edd3-4b51-b5eb-91d5b24c308d.png)
